# Generated by Django 5.2.7 on 2025-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioUnificado',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID', db_column='id_usuario')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('password', models.CharField(db_column='senha_hash', max_length=128, verbose_name='HashSenha')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=150, verbose_name='NomeCompleto')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('rg', models.CharField(blank=True, max_length=10, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone_celular', models.CharField(max_length=20, verbose_name='Telefone Celular')),
                ('telefone_fixo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo')),
                ('endereco_atual', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Atual')),
                ('nome_pai', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome da Mãe')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (m)')),
                ('doenca_cronica', models.CharField(blank=True, max_length=150, null=True, verbose_name='Doença Crônica')),
                ('deficencia', models.CharField(blank=True, max_length=150, null=True, db_column='deficiencia', verbose_name='Deficiência')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
